#!/bin/bash
# The `bash HOWTO` command, given at the command line within the `mdgBookSVG8Kit-main` directory
# in your computer, will automatically carry out the following steps leading to the creation of the 
# collection book: `mdgBookSVG8v1.pdf`.
# 
# Create three sub-folders: `bin`, `images`, `res`, under the `mdgBookSVG8-main` directory
#		`bin` - folder for Bash files: mdg87mid+svg.sh, mdg82midRndN+svg.sh, mdgEntriesSVG2.sh
#		`images` - folder for image files for book cover/title page: 1ed.png, FrontCover.pdf
# 	`res` - folder for ABC, SVG, PDF output files; initially contains: 
#		ludus-part1-D.abc - table of measures for Part I of the minuets
#		ludus-part2-D.abc - table of measures for Part II of the minuets
#		hyperref.cfg - file containing the \hypersetup{} keyvalues for the \hyperref pkg
#		mdg8.bib - bibliography file for the book
#		mdgBookSVG8v1.tex - main LaTeX file for book 
#		mdgBookSVG8v1-cover.tex - LaTeX file for cover page

	mkdir bin images res
	mv *.sh bin
	mv 1ed.png images; mv FrontCover.pdf images
	mv ludus-*.abc res
	mv hyperref.cfg res; mv mdg8.bib res
	mv *.tex res

# Change directory res folder then, for each  Bash file in `bin`, create a link 
# from `bib` to `res`

	cd res 
	ln -s ../bin/*.sh . 

# Within `res` directory, generate nnn MDGs (nnn is number of MDG minuet-trios in book to be created)
# For 250 minuets to be generated: nnn=250. Here we generate 50 

	./mdg82midRndN+svg.sh 50

# Generate a list of SVGs created by the previous step:

	ls --color=never ldmt-*.svg > svgList.txt

# Create a list of figure entries for LaTeX file; *.pdf_tex files are also created using inkscape

	./mdgEntriesSVG2.sh svgList.txt

# Change the font sizes of titles and subtitles in each ldmt-*.pdf_tex file

	sed -i 's/\\textbf{ldmt/\\footnotesize \\tt {ldmt/g' ldmt-*.pdf_tex
	sed -i 's/\\textbf{:/\\footnotesize \\tt {:/g' ldmt-*.pdf_tex
	sed -i 's/\\textbf{Perm\./\\footnotesize \\tt {Perm\.\\/' ldmt-*.pdf_tex
#	sed -i 's/{l}1\\end/{l} \\tt 1\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}2\\end/{l}\\tt 2\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}3\\end/{l}\\tt 3\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}4\\end/{l}\\tt 4\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}5\\end/{l}\\tt 5\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}6\\end/{l}\\tt 6\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}7\\end/{l}\\tt 7\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}8\\end/{l}\\tt 8\\end/g' ldmt-*.pdf_tex
#	sed -i 's/{l}9\\end/{l}\\tt 9\\end/g' ldmt-*.pdf_tex
	sed -i 's/\\textbf{= 120/\\footnotesize \\tt {= 120/' ldmt-*.pdf_tex
	sed -i 's/\[t\]{c}\\textit{3}/\[t\]{c}\\textit{\\scriptsize 3}/g' ldmt-*.pdf_tex

# Move svgList.txt.output to svgList.tex

	cp svgList.txt.output svgList.tex

# Remove trailing `001` from each svgList.tex entry 

	sed -i.OLD 's/001}/}/g' svgList.tex
	sed -i.OLD 's/001.mid}/.mid}/g' svgList.tex

# Create SVGs for the ludus-part1-D.pdf/ludus-part2-D.pdf (tables of measures); 
# also corresponding *pdf_tex files using inkscape

	abcm2ps -v -O= ludus-part1-D.abc
	inkscape --export-filename=ludus-part1-D001.pdf --export-area-drawing --export-latex ludus-part1-D001.svg
	inkscape --export-filename=ludus-part1-D002.pdf --export-area-drawing --export-latex ludus-part1-D002.svg
	
	abcm2ps -v -O= ludus-part2-D.abc
	inkscape --export-filename=ludus-part2-D001.pdf --export-area-drawing --export-latex ludus-part2-D001.svg
	inkscape --export-filename=ludus-part2-D002.pdf --export-area-drawing --export-latex ludus-part2-D002.svg


##	add \url{---}for URL; change to scriptsize

	sed -i.OLD 's/1\.2\.3\.4\.5\.6\.7\.8\.9/\\small \\tt Roll Outcomes as Parts: 1\.2\.3\.4\.5\.6\.7\.8\.9/' ludus-part1-D001.pdf_tex
	sed -i.OLD '/put(0.31773628,1.28500584)/s/\\textit{3}/\\textit{${}$3}/' ludus-part1-D001.pdf_tex
	sed -i.OLD 's/\[from http/\\scriptsize\[from \\url{http/g' ludus-part1-D001.pdf_tex
	sed -i.OLD 's/31c.pdf\]/31c.pdf}\]/g' ludus-part1-D001.pdf_tex

	sed -i.OLD 's/1\.2\.3\.4\.5\.6\.7\.8\.9/\\small \\tt Roll Outcomes as Parts: 1\.2\.3\.4\.5\.6\.7\.8\.9/' ludus-part2-D001.pdf_tex
	sed -i.OLD '/put(0.28950565,1.22414527)/s/\\textit{3}/\\textit{${}$3}/' ludus-part2-D001.pdf_tex
	sed -i.OLD 's/\[from http/\\scriptsize\[from \\url{http/g' ludus-part2-D001.pdf_tex
	sed -i.OLD 's/31c.pdf\]/31c.pdf}\]/g' ludus-part2-D001.pdf_tex

##	- add "\scriptsize" before every 3-plet" 
##	- change font for measure numbers from italics (it) to typewriter (tt) 

	sed -i.OLD 's/\[t\]{c}\\textit{3}/\[t\]{c}\\textit{\\scriptsize 3}/g' ludus-part*.pdf_tex
	sed -i.OLD 's/\[t\]{l}\\textit{/\[t\]{c}\\texttt{\\footnotesize /g' ludus-part*.pdf_tex

# Generate the PDF

	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG8v1.tex
	bibtex mdgBookSVG8v1.aux
	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG8v1.tex
	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG8v1.tex

###
##
#
